
// This file has been generated by the GUI designer. Do not modify.
namespace Fittings
{
	public partial class FittingDlg
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Button buttonSave;
		
		private global::Gtk.Button buttonCancel;
		
		private global::Gtk.Notebook notebook1;
		
		private global::Gtk.Table table1;
		
		private global::Gamma.Widgets.yEntryReference bodyMaterialReference;
		
		private global::Gamma.GtkWidgets.yEntry codeEntry;
		
		private global::Gamma.Widgets.yEntryReference connectionTypeRreference;
		
		private global::Gamma.Widgets.yEntryReference fittingTypeReference;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gamma.GtkWidgets.yTextView commentTextview;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gamma.Widgets.yEnumComboBox diameterUnitscombobox;
		
		private global::Gamma.Widgets.ySpecComboBox diameterCombobox;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gamma.Widgets.yEnumComboBox pressureUnitscombobox;
		
		private global::Gamma.Widgets.ySpecComboBox pressureCombobox;
		
		private global::Gtk.Label label10;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.Label label8;
		
		private global::Gtk.Label label9;
		
		private global::Gtk.Label Давление;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.VBox vboxPrice;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		
		private global::QSOrmProject.RepresentationTreeView treeviewPrice;
		
		private global::Gtk.Label label3;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Fittings.FittingDlg
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Fittings.FittingDlg";
			// Container child Fittings.FittingDlg.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonSave = new global::Gtk.Button ();
			this.buttonSave.CanFocus = true;
			this.buttonSave.Name = "buttonSave";
			this.buttonSave.UseUnderline = true;
			this.buttonSave.Label = global::Mono.Unix.Catalog.GetString ("Сохранить");
			this.hbox1.Add (this.buttonSave);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonSave]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = global::Mono.Unix.Catalog.GetString ("Отменить");
			this.hbox1.Add (this.buttonCancel);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonCancel]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 0;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.table1 = new global::Gtk.Table (((uint)(7)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.bodyMaterialReference = new global::Gamma.Widgets.yEntryReference ();
			this.bodyMaterialReference.Events = ((global::Gdk.EventMask)(256));
			this.bodyMaterialReference.Name = "bodyMaterialReference";
			this.table1.Add (this.bodyMaterialReference);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.bodyMaterialReference]));
			w4.TopAttach = ((uint)(5));
			w4.BottomAttach = ((uint)(6));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.codeEntry = new global::Gamma.GtkWidgets.yEntry ();
			this.codeEntry.CanFocus = true;
			this.codeEntry.Name = "codeEntry";
			this.codeEntry.IsEditable = true;
			this.codeEntry.InvisibleChar = '●';
			this.table1.Add (this.codeEntry);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.codeEntry]));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.connectionTypeRreference = new global::Gamma.Widgets.yEntryReference ();
			this.connectionTypeRreference.Events = ((global::Gdk.EventMask)(256));
			this.connectionTypeRreference.Name = "connectionTypeRreference";
			this.table1.Add (this.connectionTypeRreference);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.connectionTypeRreference]));
			w6.TopAttach = ((uint)(4));
			w6.BottomAttach = ((uint)(5));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.fittingTypeReference = new global::Gamma.Widgets.yEntryReference ();
			this.fittingTypeReference.Events = ((global::Gdk.EventMask)(256));
			this.fittingTypeReference.Name = "fittingTypeReference";
			this.table1.Add (this.fittingTypeReference);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.fittingTypeReference]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.commentTextview = new global::Gamma.GtkWidgets.yTextView ();
			this.commentTextview.CanFocus = true;
			this.commentTextview.Name = "commentTextview";
			this.GtkScrolledWindow.Add (this.commentTextview);
			this.table1.Add (this.GtkScrolledWindow);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.GtkScrolledWindow]));
			w9.TopAttach = ((uint)(6));
			w9.BottomAttach = ((uint)(7));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(2));
			// Container child table1.Gtk.Table+TableChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.diameterUnitscombobox = new global::Gamma.Widgets.yEnumComboBox ();
			this.diameterUnitscombobox.Name = "diameterUnitscombobox";
			this.diameterUnitscombobox.ShowSpecialStateAll = false;
			this.diameterUnitscombobox.ShowSpecialStateNot = false;
			this.diameterUnitscombobox.UseShortTitle = false;
			this.diameterUnitscombobox.DefaultFirst = true;
			this.hbox4.Add (this.diameterUnitscombobox);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.diameterUnitscombobox]));
			w10.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.diameterCombobox = new global::Gamma.Widgets.ySpecComboBox ();
			this.diameterCombobox.Name = "diameterCombobox";
			this.diameterCombobox.AddIfNotExist = false;
			this.diameterCombobox.DefaultFirst = false;
			this.diameterCombobox.ShowSpecialStateAll = false;
			this.diameterCombobox.ShowSpecialStateNot = true;
			this.hbox4.Add (this.diameterCombobox);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.diameterCombobox]));
			w11.Position = 1;
			this.table1.Add (this.hbox4);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1 [this.hbox4]));
			w12.TopAttach = ((uint)(2));
			w12.BottomAttach = ((uint)(3));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.pressureUnitscombobox = new global::Gamma.Widgets.yEnumComboBox ();
			this.pressureUnitscombobox.Name = "pressureUnitscombobox";
			this.pressureUnitscombobox.ShowSpecialStateAll = false;
			this.pressureUnitscombobox.ShowSpecialStateNot = false;
			this.pressureUnitscombobox.UseShortTitle = false;
			this.pressureUnitscombobox.DefaultFirst = true;
			this.hbox5.Add (this.pressureUnitscombobox);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.pressureUnitscombobox]));
			w13.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.pressureCombobox = new global::Gamma.Widgets.ySpecComboBox ();
			this.pressureCombobox.Name = "pressureCombobox";
			this.pressureCombobox.AddIfNotExist = false;
			this.pressureCombobox.DefaultFirst = false;
			this.pressureCombobox.ShowSpecialStateAll = false;
			this.pressureCombobox.ShowSpecialStateNot = true;
			this.hbox5.Add (this.pressureCombobox);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.pressureCombobox]));
			w14.Position = 1;
			this.table1.Add (this.hbox5);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1 [this.hbox5]));
			w15.TopAttach = ((uint)(3));
			w15.BottomAttach = ((uint)(4));
			w15.LeftAttach = ((uint)(1));
			w15.RightAttach = ((uint)(2));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.Xalign = 1F;
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Тип арматуры:");
			this.table1.Add (this.label10);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1 [this.label10]));
			w16.TopAttach = ((uint)(1));
			w16.BottomAttach = ((uint)(2));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xalign = 1F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Диаметр:");
			this.table1.Add (this.label2);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1 [this.label2]));
			w17.TopAttach = ((uint)(2));
			w17.BottomAttach = ((uint)(3));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.Xalign = 1F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Вид соединения:");
			this.table1.Add (this.label4);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1 [this.label4]));
			w18.TopAttach = ((uint)(4));
			w18.BottomAttach = ((uint)(5));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.Xalign = 1F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Материал корпуса:");
			this.table1.Add (this.label7);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1 [this.label7]));
			w19.TopAttach = ((uint)(5));
			w19.BottomAttach = ((uint)(6));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.Xalign = 1F;
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Артикул:");
			this.table1.Add (this.label8);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table1 [this.label8]));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.Xalign = 1F;
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Комментарий:");
			this.table1.Add (this.label9);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table1 [this.label9]));
			w21.TopAttach = ((uint)(6));
			w21.BottomAttach = ((uint)(7));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.Давление = new global::Gtk.Label ();
			this.Давление.Name = "Давление";
			this.Давление.Xalign = 1F;
			this.Давление.LabelProp = global::Mono.Unix.Catalog.GetString ("Давление:");
			this.table1.Add (this.Давление);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table1 [this.Давление]));
			w22.TopAttach = ((uint)(3));
			w22.BottomAttach = ((uint)(4));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			this.notebook1.Add (this.table1);
			// Notebook tab
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Основное");
			this.notebook1.SetTabLabel (this.table1, this.label1);
			this.label1.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vboxPrice = new global::Gtk.VBox ();
			this.vboxPrice.Name = "vboxPrice";
			this.vboxPrice.Spacing = 6;
			// Container child vboxPrice.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.treeviewPrice = new global::QSOrmProject.RepresentationTreeView ();
			this.treeviewPrice.CanFocus = true;
			this.treeviewPrice.Name = "treeviewPrice";
			this.GtkScrolledWindow1.Add (this.treeviewPrice);
			this.vboxPrice.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vboxPrice [this.GtkScrolledWindow1]));
			w25.Position = 1;
			this.notebook1.Add (this.vboxPrice);
			global::Gtk.Notebook.NotebookChild w26 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vboxPrice]));
			w26.Position = 1;
			// Notebook tab
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Цены");
			this.notebook1.SetTabLabel (this.vboxPrice, this.label3);
			this.label3.ShowAll ();
			this.vbox1.Add (this.notebook1);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.notebook1]));
			w27.Position = 1;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.buttonSave.Clicked += new global::System.EventHandler (this.OnButtonSaveClicked);
			this.buttonCancel.Clicked += new global::System.EventHandler (this.OnButtonCancelClicked);
			this.pressureUnitscombobox.Changed += new global::System.EventHandler (this.OnPressureUnitscomboboxChanged);
			this.diameterUnitscombobox.Changed += new global::System.EventHandler (this.OnDiameterUnitscomboboxChanged);
		}
	}
}
