
// This file has been generated by the GUI designer. Do not modify.
namespace Fittings
{
	public partial class FittingsFlt
	{
		private global::Gtk.Table table1;
		
		private global::QSOrmProject.EntryReference bodyMaterialReference;
		
		private global::QSOrmProject.EntryReference connectionTypeRreference;
		
		private global::QSOrmProject.EntryReference fittingTypeReference;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gamma.Widgets.yEnumComboBox diameterUnitscombobox;
		
		private global::Gamma.Widgets.ySpecComboBox diameterCombobox;
		
		private global::Gtk.HBox hbox6;
		
		private global::Gamma.Widgets.yEnumComboBox pressureUnitscombobox;
		
		private global::Gamma.Widgets.ySpecComboBox pressureCombobox;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Label label5;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Fittings.FittingsFlt
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Fittings.FittingsFlt";
			// Container child Fittings.FittingsFlt.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(4)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.bodyMaterialReference = new global::QSOrmProject.EntryReference ();
			this.bodyMaterialReference.Events = ((global::Gdk.EventMask)(256));
			this.bodyMaterialReference.Name = "bodyMaterialReference";
			this.table1.Add (this.bodyMaterialReference);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.bodyMaterialReference]));
			w1.TopAttach = ((uint)(1));
			w1.BottomAttach = ((uint)(2));
			w1.LeftAttach = ((uint)(3));
			w1.RightAttach = ((uint)(4));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.connectionTypeRreference = new global::QSOrmProject.EntryReference ();
			this.connectionTypeRreference.Events = ((global::Gdk.EventMask)(256));
			this.connectionTypeRreference.Name = "connectionTypeRreference";
			this.table1.Add (this.connectionTypeRreference);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.connectionTypeRreference]));
			w2.LeftAttach = ((uint)(3));
			w2.RightAttach = ((uint)(4));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.fittingTypeReference = new global::QSOrmProject.EntryReference ();
			this.fittingTypeReference.Events = ((global::Gdk.EventMask)(256));
			this.fittingTypeReference.Name = "fittingTypeReference";
			this.table1.Add (this.fittingTypeReference);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.fittingTypeReference]));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.diameterUnitscombobox = new global::Gamma.Widgets.yEnumComboBox ();
			this.diameterUnitscombobox.Name = "diameterUnitscombobox";
			this.diameterUnitscombobox.ShowSpecialStateAll = false;
			this.diameterUnitscombobox.ShowSpecialStateNot = false;
			this.diameterUnitscombobox.UseShortTitle = false;
			this.diameterUnitscombobox.DefaultFirst = true;
			this.hbox5.Add (this.diameterUnitscombobox);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.diameterUnitscombobox]));
			w4.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.diameterCombobox = new global::Gamma.Widgets.ySpecComboBox ();
			this.diameterCombobox.Name = "diameterCombobox";
			this.diameterCombobox.AddIfNotExist = false;
			this.diameterCombobox.DefaultFirst = false;
			this.diameterCombobox.ShowSpecialStateAll = false;
			this.diameterCombobox.ShowSpecialStateNot = true;
			this.hbox5.Add (this.diameterCombobox);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.diameterCombobox]));
			w5.Position = 1;
			this.table1.Add (this.hbox5);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.hbox5]));
			w6.TopAttach = ((uint)(2));
			w6.BottomAttach = ((uint)(3));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.pressureUnitscombobox = new global::Gamma.Widgets.yEnumComboBox ();
			this.pressureUnitscombobox.Name = "pressureUnitscombobox";
			this.pressureUnitscombobox.ShowSpecialStateAll = false;
			this.pressureUnitscombobox.ShowSpecialStateNot = false;
			this.pressureUnitscombobox.UseShortTitle = false;
			this.pressureUnitscombobox.DefaultFirst = true;
			this.hbox6.Add (this.pressureUnitscombobox);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.pressureUnitscombobox]));
			w7.Position = 0;
			// Container child hbox6.Gtk.Box+BoxChild
			this.pressureCombobox = new global::Gamma.Widgets.ySpecComboBox ();
			this.pressureCombobox.Name = "pressureCombobox";
			this.pressureCombobox.AddIfNotExist = false;
			this.pressureCombobox.DefaultFirst = false;
			this.pressureCombobox.ShowSpecialStateAll = false;
			this.pressureCombobox.ShowSpecialStateNot = true;
			this.hbox6.Add (this.pressureCombobox);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.pressureCombobox]));
			w8.Position = 1;
			this.table1.Add (this.hbox6);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.hbox6]));
			w9.TopAttach = ((uint)(2));
			w9.BottomAttach = ((uint)(3));
			w9.LeftAttach = ((uint)(3));
			w9.RightAttach = ((uint)(4));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 1F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Название");
			this.table1.Add (this.label1);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.label1]));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xalign = 1F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Диаметр");
			this.table1.Add (this.label2);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.label2]));
			w11.TopAttach = ((uint)(2));
			w11.BottomAttach = ((uint)(3));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xalign = 1F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Давление");
			this.table1.Add (this.label3);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1 [this.label3]));
			w12.TopAttach = ((uint)(2));
			w12.BottomAttach = ((uint)(3));
			w12.LeftAttach = ((uint)(2));
			w12.RightAttach = ((uint)(3));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.Xalign = 1F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Тип соединения");
			this.table1.Add (this.label4);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1 [this.label4]));
			w13.LeftAttach = ((uint)(2));
			w13.RightAttach = ((uint)(3));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.Xalign = 1F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Материал корпуса");
			this.table1.Add (this.label5);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1 [this.label5]));
			w14.TopAttach = ((uint)(1));
			w14.BottomAttach = ((uint)(2));
			w14.LeftAttach = ((uint)(2));
			w14.RightAttach = ((uint)(3));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.table1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.pressureUnitscombobox.Changed += new global::System.EventHandler (this.OnPressureUnitscomboboxChanged);
			this.pressureCombobox.Changed += new global::System.EventHandler (this.OnPressureComboboxChanged);
			this.diameterUnitscombobox.Changed += new global::System.EventHandler (this.OnDiameterUnitscomboboxChanged);
			this.diameterCombobox.Changed += new global::System.EventHandler (this.OnDiameterComboboxChanged);
			this.fittingTypeReference.Changed += new global::System.EventHandler (this.OnFittingTypeReferenceChanged);
			this.connectionTypeRreference.Changed += new global::System.EventHandler (this.OnConnectionTypeRreferenceChanged);
			this.bodyMaterialReference.Changed += new global::System.EventHandler (this.OnBodyMaterialReferenceChanged);
		}
	}
}
