
// This file has been generated by the GUI designer. Do not modify.
namespace Fittings
{
	public partial class MultiEditXLSRows
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.HBox hbox6;
		
		private global::Gtk.Button buttonApply;
		
		private global::Gtk.Button buttonCancel;
		
		private global::Gtk.Table table1;
		
		private global::Gamma.Widgets.yEntryReference bodyMaterialReference;
		
		private global::Gtk.CheckButton checkComments;
		
		private global::Gtk.CheckButton checkConnections;
		
		private global::Gtk.CheckButton checkDiameter;
		
		private global::Gtk.CheckButton checkMaterial;
		
		private global::Gtk.CheckButton checkModel;
		
		private global::Gtk.CheckButton checkPressure;
		
		private global::Gtk.CheckButton checkType;
		
		private global::Gamma.GtkWidgets.yEntry codeEntry;
		
		private global::Gamma.Widgets.yEntryReference connectionTypeRreference;
		
		private global::Gamma.Widgets.yEntryReference fittingTypeReference;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gamma.GtkWidgets.yTextView commentTextview;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gamma.Widgets.yEnumComboBox diameterUnitscombobox;
		
		private global::Gamma.Widgets.ySpecComboBox diameterCombobox;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gamma.Widgets.yEnumComboBox pressureUnitscombobox;
		
		private global::Gamma.Widgets.ySpecComboBox pressureCombobox;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Label labelInfo;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Fittings.MultiEditXLSRows
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Fittings.MultiEditXLSRows";
			// Container child Fittings.MultiEditXLSRows.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.buttonApply = new global::Gtk.Button ();
			this.buttonApply.CanFocus = true;
			this.buttonApply.Name = "buttonApply";
			this.buttonApply.UseStock = true;
			this.buttonApply.UseUnderline = true;
			this.buttonApply.Label = "gtk-apply";
			this.hbox6.Add (this.buttonApply);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.buttonApply]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.hbox6.Add (this.buttonCancel);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.buttonCancel]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.vbox1.Add (this.hbox6);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox6]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(8)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.bodyMaterialReference = new global::Gamma.Widgets.yEntryReference ();
			this.bodyMaterialReference.Events = ((global::Gdk.EventMask)(256));
			this.bodyMaterialReference.Name = "bodyMaterialReference";
			this.table1.Add (this.bodyMaterialReference);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.bodyMaterialReference]));
			w4.TopAttach = ((uint)(6));
			w4.BottomAttach = ((uint)(7));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.checkComments = new global::Gtk.CheckButton ();
			this.checkComments.CanFocus = true;
			this.checkComments.Name = "checkComments";
			this.checkComments.Label = global::Mono.Unix.Catalog.GetString ("Комментарий");
			this.checkComments.Active = true;
			this.checkComments.DrawIndicator = true;
			this.checkComments.UseUnderline = true;
			this.table1.Add (this.checkComments);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkComments]));
			w5.TopAttach = ((uint)(7));
			w5.BottomAttach = ((uint)(8));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.checkConnections = new global::Gtk.CheckButton ();
			this.checkConnections.CanFocus = true;
			this.checkConnections.Name = "checkConnections";
			this.checkConnections.Label = global::Mono.Unix.Catalog.GetString ("Соединения");
			this.checkConnections.Active = true;
			this.checkConnections.DrawIndicator = true;
			this.checkConnections.UseUnderline = true;
			this.table1.Add (this.checkConnections);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkConnections]));
			w6.TopAttach = ((uint)(5));
			w6.BottomAttach = ((uint)(6));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.checkDiameter = new global::Gtk.CheckButton ();
			this.checkDiameter.CanFocus = true;
			this.checkDiameter.Name = "checkDiameter";
			this.checkDiameter.Label = global::Mono.Unix.Catalog.GetString ("Диаметр");
			this.checkDiameter.Active = true;
			this.checkDiameter.DrawIndicator = true;
			this.checkDiameter.UseUnderline = true;
			this.table1.Add (this.checkDiameter);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkDiameter]));
			w7.TopAttach = ((uint)(3));
			w7.BottomAttach = ((uint)(4));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.checkMaterial = new global::Gtk.CheckButton ();
			this.checkMaterial.CanFocus = true;
			this.checkMaterial.Name = "checkMaterial";
			this.checkMaterial.Label = global::Mono.Unix.Catalog.GetString ("Материал");
			this.checkMaterial.Active = true;
			this.checkMaterial.DrawIndicator = true;
			this.checkMaterial.UseUnderline = true;
			this.table1.Add (this.checkMaterial);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkMaterial]));
			w8.TopAttach = ((uint)(6));
			w8.BottomAttach = ((uint)(7));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.checkModel = new global::Gtk.CheckButton ();
			this.checkModel.CanFocus = true;
			this.checkModel.Name = "checkModel";
			this.checkModel.Label = global::Mono.Unix.Catalog.GetString ("Модель");
			this.checkModel.Active = true;
			this.checkModel.DrawIndicator = true;
			this.checkModel.UseUnderline = true;
			this.table1.Add (this.checkModel);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkModel]));
			w9.TopAttach = ((uint)(1));
			w9.BottomAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.checkPressure = new global::Gtk.CheckButton ();
			this.checkPressure.CanFocus = true;
			this.checkPressure.Name = "checkPressure";
			this.checkPressure.Label = global::Mono.Unix.Catalog.GetString ("Давление");
			this.checkPressure.Active = true;
			this.checkPressure.DrawIndicator = true;
			this.checkPressure.UseUnderline = true;
			this.table1.Add (this.checkPressure);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkPressure]));
			w10.TopAttach = ((uint)(4));
			w10.BottomAttach = ((uint)(5));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.checkType = new global::Gtk.CheckButton ();
			this.checkType.CanFocus = true;
			this.checkType.Name = "checkType";
			this.checkType.Label = global::Mono.Unix.Catalog.GetString ("Тип");
			this.checkType.Active = true;
			this.checkType.DrawIndicator = true;
			this.checkType.UseUnderline = true;
			this.table1.Add (this.checkType);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkType]));
			w11.TopAttach = ((uint)(2));
			w11.BottomAttach = ((uint)(3));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.codeEntry = new global::Gamma.GtkWidgets.yEntry ();
			this.codeEntry.CanFocus = true;
			this.codeEntry.Name = "codeEntry";
			this.codeEntry.IsEditable = true;
			this.codeEntry.InvisibleChar = '●';
			this.table1.Add (this.codeEntry);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1 [this.codeEntry]));
			w12.TopAttach = ((uint)(1));
			w12.BottomAttach = ((uint)(2));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.connectionTypeRreference = new global::Gamma.Widgets.yEntryReference ();
			this.connectionTypeRreference.Events = ((global::Gdk.EventMask)(256));
			this.connectionTypeRreference.Name = "connectionTypeRreference";
			this.table1.Add (this.connectionTypeRreference);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1 [this.connectionTypeRreference]));
			w13.TopAttach = ((uint)(5));
			w13.BottomAttach = ((uint)(6));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.fittingTypeReference = new global::Gamma.Widgets.yEntryReference ();
			this.fittingTypeReference.Events = ((global::Gdk.EventMask)(256));
			this.fittingTypeReference.Name = "fittingTypeReference";
			this.table1.Add (this.fittingTypeReference);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1 [this.fittingTypeReference]));
			w14.TopAttach = ((uint)(2));
			w14.BottomAttach = ((uint)(3));
			w14.LeftAttach = ((uint)(1));
			w14.RightAttach = ((uint)(2));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.commentTextview = new global::Gamma.GtkWidgets.yTextView ();
			this.commentTextview.WidthRequest = 50;
			this.commentTextview.CanFocus = true;
			this.commentTextview.Name = "commentTextview";
			this.GtkScrolledWindow.Add (this.commentTextview);
			this.table1.Add (this.GtkScrolledWindow);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1 [this.GtkScrolledWindow]));
			w16.TopAttach = ((uint)(7));
			w16.BottomAttach = ((uint)(8));
			w16.LeftAttach = ((uint)(1));
			w16.RightAttach = ((uint)(2));
			// Container child table1.Gtk.Table+TableChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.diameterUnitscombobox = new global::Gamma.Widgets.yEnumComboBox ();
			this.diameterUnitscombobox.Name = "diameterUnitscombobox";
			this.diameterUnitscombobox.ShowSpecialStateAll = false;
			this.diameterUnitscombobox.ShowSpecialStateNot = false;
			this.diameterUnitscombobox.UseShortTitle = false;
			this.diameterUnitscombobox.DefaultFirst = true;
			this.hbox4.Add (this.diameterUnitscombobox);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.diameterUnitscombobox]));
			w17.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.diameterCombobox = new global::Gamma.Widgets.ySpecComboBox ();
			this.diameterCombobox.Name = "diameterCombobox";
			this.diameterCombobox.AddIfNotExist = false;
			this.diameterCombobox.DefaultFirst = false;
			this.diameterCombobox.ShowSpecialStateAll = false;
			this.diameterCombobox.ShowSpecialStateNot = true;
			this.hbox4.Add (this.diameterCombobox);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.diameterCombobox]));
			w18.Position = 1;
			this.table1.Add (this.hbox4);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1 [this.hbox4]));
			w19.TopAttach = ((uint)(3));
			w19.BottomAttach = ((uint)(4));
			w19.LeftAttach = ((uint)(1));
			w19.RightAttach = ((uint)(2));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.pressureUnitscombobox = new global::Gamma.Widgets.yEnumComboBox ();
			this.pressureUnitscombobox.Name = "pressureUnitscombobox";
			this.pressureUnitscombobox.ShowSpecialStateAll = false;
			this.pressureUnitscombobox.ShowSpecialStateNot = false;
			this.pressureUnitscombobox.UseShortTitle = false;
			this.pressureUnitscombobox.DefaultFirst = true;
			this.hbox5.Add (this.pressureUnitscombobox);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.pressureUnitscombobox]));
			w20.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.pressureCombobox = new global::Gamma.Widgets.ySpecComboBox ();
			this.pressureCombobox.Name = "pressureCombobox";
			this.pressureCombobox.AddIfNotExist = false;
			this.pressureCombobox.DefaultFirst = false;
			this.pressureCombobox.ShowSpecialStateAll = false;
			this.pressureCombobox.ShowSpecialStateNot = true;
			this.hbox5.Add (this.pressureCombobox);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.pressureCombobox]));
			w21.Position = 1;
			this.table1.Add (this.hbox5);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table1 [this.hbox5]));
			w22.TopAttach = ((uint)(4));
			w22.BottomAttach = ((uint)(5));
			w22.LeftAttach = ((uint)(1));
			w22.RightAttach = ((uint)(2));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 1F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Редактируем:");
			this.table1.Add (this.label1);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table1 [this.label1]));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelInfo = new global::Gtk.Label ();
			this.labelInfo.Name = "labelInfo";
			this.labelInfo.LabelProp = global::Mono.Unix.Catalog.GetString ("label2");
			this.table1.Add (this.labelInfo);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelInfo]));
			w24.LeftAttach = ((uint)(1));
			w24.RightAttach = ((uint)(2));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox1.Add (this.table1);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table1]));
			w25.Position = 1;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.buttonApply.Clicked += new global::System.EventHandler (this.OnButtonApplyClicked);
			this.buttonCancel.Clicked += new global::System.EventHandler (this.OnButtonCancelClicked);
			this.pressureUnitscombobox.Changed += new global::System.EventHandler (this.OnPressureUnitscomboboxChanged);
			this.diameterUnitscombobox.Changed += new global::System.EventHandler (this.OnDiameterUnitscomboboxChanged);
			this.checkType.Clicked += new global::System.EventHandler (this.OnCheckTypeClicked);
			this.checkPressure.Clicked += new global::System.EventHandler (this.OnCheckPressureClicked);
			this.checkModel.Clicked += new global::System.EventHandler (this.OnCheckModelClicked);
			this.checkMaterial.Clicked += new global::System.EventHandler (this.OnCheckMaterialClicked);
			this.checkDiameter.Clicked += new global::System.EventHandler (this.OnCheckDiameterClicked);
			this.checkConnections.Clicked += new global::System.EventHandler (this.OnCheckConnectionsClicked);
			this.checkComments.Clicked += new global::System.EventHandler (this.OnCheckCommentsClicked);
		}
	}
}
