
// This file has been generated by the GUI designer. Do not modify.
namespace Fittings
{
	public partial class ProjectDlg
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.HBox hbox6;
		
		private global::Gtk.Button buttonSave;
		
		private global::Gtk.Button buttonCancel;
		
		private global::Gtk.Table table2;
		
		private global::Gamma.GtkWidgets.yEntry customerEntry;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gamma.GtkWidgets.yTreeView projectTreeView;
		
		private global::Gtk.Label label11;
		
		private global::Gtk.Label label12;
		
		private global::Gamma.GtkWidgets.yEntry projectNameEntry;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Button buttonAdd;
		
		private global::Gtk.Button buttonEdit1;
		
		private global::Gtk.Button buttonRemove;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Fittings.ProjectDlg
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Fittings.ProjectDlg";
			// Container child Fittings.ProjectDlg.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.buttonSave = new global::Gtk.Button ();
			this.buttonSave.CanFocus = true;
			this.buttonSave.Name = "buttonSave";
			this.buttonSave.UseUnderline = true;
			this.buttonSave.Label = global::Mono.Unix.Catalog.GetString ("Сохранить");
			this.hbox6.Add (this.buttonSave);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.buttonSave]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = global::Mono.Unix.Catalog.GetString ("Отменить");
			this.hbox6.Add (this.buttonCancel);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.buttonCancel]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.vbox2.Add (this.hbox6);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox6]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.table2 = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.customerEntry = new global::Gamma.GtkWidgets.yEntry ();
			this.customerEntry.CanFocus = true;
			this.customerEntry.Name = "customerEntry";
			this.customerEntry.IsEditable = true;
			this.customerEntry.InvisibleChar = '●';
			this.table2.Add (this.customerEntry);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table2 [this.customerEntry]));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.projectTreeView = new global::Gamma.GtkWidgets.yTreeView ();
			this.projectTreeView.CanFocus = true;
			this.projectTreeView.Name = "projectTreeView";
			this.GtkScrolledWindow.Add (this.projectTreeView);
			this.table2.Add (this.GtkScrolledWindow);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table2 [this.GtkScrolledWindow]));
			w6.TopAttach = ((uint)(2));
			w6.BottomAttach = ((uint)(3));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.Xalign = 1F;
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Заказчик:");
			this.table2.Add (this.label11);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table2 [this.label11]));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.Xalign = 1F;
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Название проекта:");
			this.table2.Add (this.label12);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table2 [this.label12]));
			w8.TopAttach = ((uint)(1));
			w8.BottomAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.projectNameEntry = new global::Gamma.GtkWidgets.yEntry ();
			this.projectNameEntry.CanFocus = true;
			this.projectNameEntry.Name = "projectNameEntry";
			this.projectNameEntry.IsEditable = true;
			this.projectNameEntry.InvisibleChar = '●';
			this.table2.Add (this.projectNameEntry);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table2 [this.projectNameEntry]));
			w9.TopAttach = ((uint)(1));
			w9.BottomAttach = ((uint)(2));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(2));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox2.Add (this.table2);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.table2]));
			w10.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.buttonAdd = new global::Gtk.Button ();
			this.buttonAdd.CanFocus = true;
			this.buttonAdd.Name = "buttonAdd";
			this.buttonAdd.UseUnderline = true;
			this.buttonAdd.Label = global::Mono.Unix.Catalog.GetString ("Добавить");
			this.hbox2.Add (this.buttonAdd);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.buttonAdd]));
			w11.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.buttonEdit1 = new global::Gtk.Button ();
			this.buttonEdit1.CanFocus = true;
			this.buttonEdit1.Name = "buttonEdit1";
			this.buttonEdit1.UseUnderline = true;
			this.buttonEdit1.Label = global::Mono.Unix.Catalog.GetString ("Изменить арматуру");
			this.hbox2.Add (this.buttonEdit1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.buttonEdit1]));
			w12.Position = 1;
			// Container child hbox2.Gtk.Box+BoxChild
			this.buttonRemove = new global::Gtk.Button ();
			this.buttonRemove.CanFocus = true;
			this.buttonRemove.Name = "buttonRemove";
			this.buttonRemove.UseUnderline = true;
			this.buttonRemove.Label = global::Mono.Unix.Catalog.GetString ("Удалить");
			this.hbox2.Add (this.buttonRemove);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.buttonRemove]));
			w13.Position = 2;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.buttonSave.Clicked += new global::System.EventHandler (this.OnButtonSaveClicked);
			this.buttonCancel.Clicked += new global::System.EventHandler (this.OnButtonCancelClicked);
			this.buttonAdd.Clicked += new global::System.EventHandler (this.OnButtonAddClicked);
			this.buttonEdit1.Clicked += new global::System.EventHandler (this.OnButtonEdit1Clicked);
			this.buttonRemove.Clicked += new global::System.EventHandler (this.OnButtonRemoveClicked);
		}
	}
}
